name: Build-FFmpeg-With-NVENC-AMF-VTB
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt update
          sudo apt install -y build-essential yasm nasm pkg-config libva-dev git upx cmake autoconf automake libtool

      - name: Build deps
        run: |
          chmod +x ./build-linux-x64.sh
          ./build-linux-x64.sh build-dep
          cd build_dep/nv-codec-headers
          sudo make install

      - name: Compile ffmpeg
        run: |
          chmod +x ./build-linux-x64.sh
          ./build-linux-x64.sh compile

      - name: Strip and UPX
        run: |
          strip ./output-linux-x64/bin/ffmpeg
          upx --best ./output-linux-x64/bin/ffmpeg || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-linux-x64
          path: ./output-linux-x64/bin/ffmpeg

  build-win-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mingw-w64
        run: |
          sudo apt install -y mingw-w64 build-essential yasm nasm git upx pkg-config cmake autoconf automake libtool

      - name: Build deps
        run: |
          chmod +x ./build-win-x64.sh
          ./build-win-x64.sh build-dep
          cd build_win/nv-codec-headers
          sudo make PREFIX=/usr/x86_64-w64-mingw32 install
          sudo tee /usr/local/bin/x86_64-w64-mingw32-pkg-config << 'PKGCONF'
          #!/bin/sh
          PKG_CONFIG_LIBDIR=/usr/x86_64-w64-mingw32/lib/pkgconfig exec pkg-config "$@"
          PKGCONF
          sudo chmod +x /usr/local/bin/x86_64-w64-mingw32-pkg-config

      - name: Compile windows-ffmpeg
        run: |
          chmod +x ./build-win-x64.sh
          ./build-win-x64.sh compile

      - name: Strip + UPX
        run: |
          x86_64-w64-mingw32-strip ./output-win64/bin/ffmpeg.exe
          upx --best ./output-win64/bin/ffmpeg.exe || true

      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-win-x64
          path: ./output-win64/bin/ffmpeg.exe

  build-mac-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install yasm nasm pkg-config cmake autoconf automake libtool

      - name: Build deps
        run: |
          chmod +x ./build-mac-arm.sh
          ./build-mac-arm.sh build-dep

      - name: Compile mac-arm64
        run: |
          chmod +x ./build-mac-arm.sh
          ./build-mac-arm.sh compile

      - name: Strip
        run: strip ./output-mac-arm64/bin/ffmpeg

      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-mac-arm64
          path: ./output-mac-arm64/bin/ffmpeg
